services:
  - type: web
    name: hairalyze-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node debug.js && node index.js
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
